apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-app
spec:
  selector:
    matchLabels:
      app: nginx-demo-app
  template:
    metadata:
      labels:
        app: nginx-demo-app
    spec:
      containers:
        - name: app
          image: nginx:1.14
          ports:
            - name: http
              containerPort: 80
              protocol: TCP